### ISSUE TITLE
在ios上会出现前两张图片正常，第三张就消失了，然后返回第一张的时候也消失了，退出重进会重复一样的现象

### ISSUE THREAD

**Issue by ys475972280** [MinJieLiu/react-photo-view#33]

**Comment by zhangsshuj** [comment]
我也出现一样的问题了

**Comment by Amecy** [comment]
同样发现此问题，无论iOS版本是新是旧。
排查发现插件给图片容器设置的宽高是0，但没能更新宽度。覆盖默认样式可以解决：

```less
/* fix: 修复 react-photo-view 在 iOS 上面图片可能不显示的问题 */
.PhotoView__PhotoBox {
  width: 100% !important;
  height: 100% !important;
}
```
